linters:
  disable-all: true
  enable:
    - copyloopvar
    - errcheck
    - gochecknoinits
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - whitespace

linters-settings:
  govet:
    enable:
      - nilness
  goimports:
    local-prefixes: github.com/turtlepavlo/async-queue-service

issues:
  exclude-dirs:
    - examples
  exclude-rules:
    - path: (.+)_test\.go
      linters:
        - errcheck
