package interfaces

import (
	"time"

	headerVal "github.com/turtlepavlo/async-queue-service/headers/value"
)

// Message is the envelope for all published and consumed messages.
type Message struct {
	// ID is auto-generated by the publisher if not provided.
	ID string `json:"id"`
	// Action maps to the routing key in RabbitMQ.
	Action string `json:"action"`
	// Topic maps to the exchange name in RabbitMQ.
	Topic string `json:"topic"`
	Data  any    `json:"data"`
	// ContentType defaults to "application/json". Do not use the "goqueue-" header prefix — it is reserved.
	ContentType   headerVal.ContentType      `json:"-"`
	Timestamp     time.Time                  `json:"timestamp"`
	Headers       map[string]any             `json:"-"`
	ServiceAgent  headerVal.GoquServiceAgent `json:"-"`
	schemaVersion string
}

func (m *Message) SetSchemaVersion(v string) { m.schemaVersion = v }
func (m *Message) GetSchemaVersion() string  { return m.schemaVersion }
